In [1]:
import keras
import numpy as np
import chess
import chess.pgn
import os
import chess.svg
import tensorflow as tf
from keras.utils import to_categorical

#%run chessboard.py
print(os.getcwd)
#dir_path = os.path.dirname(os.path.realpath(__file__))



class State(object):
    def __init__(self):
        self.board = chess.Board()

    def edges(self):
        return list(self.board.legal_moves)

    def value(self):
        return 0  # 0, 1 or 1/2


if __name__ == "__main__":
    s = State()
    print(s.edges())
    print('hello')
# game = chess.pgn.read_game(game)

boardd = chess.Board("6k1/1b2rpb1/3p2p1/1P3n1p/r3p3/BR6/P4PPP/3RNBK1 b - - 0 26")
squares = boardd.attacks(chess.E4)
chess.svg.board(board=boardd, squares=squares)
chess.svg.piece(chess.Piece.from_symbol("R"))
print(boardd)


#dir_path = os.path.dirname(os.path.realpath(__file__))
#print("CURRENT PATH K", dir_path)
#os.chdir("data/KingBase2019-pgn")
#os.chdir(../)
#os.chdir("data2/lol")
#%cd C:\data2\lol
#%cd C:\data/KingBase2019-pgn
#%run KingBase2019-pgn

#os.chdir("data2/lol")
# pgntest = open(os.access("data/KingBase2019-pgn", os.X_OK))
#bigdataset = os.chdir("data/KingBase2019-pgn")
file_list = [f for f in os.listdir('data/KingBase2019-pgn') if os.path.isfile(os.path.join('data/KingBase2019-pgn', f))]
if '.DS_Store' in file_list:
    file_list.remove(".DS_Store")
print(file_list)
game = 0
gn = 0
#if name != ".DS_Store":
X, Y = [], []

for number in file_list:
    # for number in os.listdir("data/KingBase2019-pgn"):
    print("WHICH FILE", number)
    pgn = open(os.path.join("data/KingBase2019-pgn",number))
    #pgn = open(os.path.join(encode(encoding="utf-8-sig"),"data2/lol",number))
    #while True:
    while game < 8000:
        try:
            headers = chess.pgn.read_game(pgn)  # print(headers.headers("Result"))
            value=headers.headers["Result"]
        except Exception:
            if headers is None:
                print("BOOOOOM")
                break
        print("Parsing game", gn)
        gn+=1
        board=headers.board()
        if(value == "0-1"):
            value = -1
        if (value == "1-0"):
            value = 1
        if (value == "1/2-1/2"):
            value = 0
        #Y.append(value)
        #print(Y)
        for move in headers.mainline_moves():
            board.push(move)
            #print(board.is_pinned(chess.WHITE, chess.C3))
            #34ser = board(board.woo)
            #print(board.fen(), "  THIS ONE?")
            #print(headers.headers["Result"])
            board.is_valid()
            encodeboard = np.zeros(64, np.uint8) #(64, np.uint8)
            for i in range(64):
                position = board.piece_at(i)
                if position is not None:
                    # print(i, pp.symbol())
                    encodeboard[i] = {"P": 1, "N": 2, "B": 3, "R": 4, "Q": 5, "K": 6, "p": 7, "n": 8, "b": 9, "r": 10, "q": 11, "k": 12} [position.symbol()]  #[position.symbol()]
            #if board.ep_square is not None:
            #    assert bstate[board.ep_square] == 0
            #    bstate[board.ep_square] = 8
            #print(board)
            encodeboard=encodeboard.reshape(8,8,1)
            game+=1
            #if(value != 0):
            X.append(encodeboard)
            
            Y.append(value)
            
            #game+=1

            #print("Total number of moves ",game)
        #Y=np.array(Y)
        #print(Y)


testarray = []
testarray2 = []
testarray.append(encodeboard)
print(testarray)
testarray = np.array(testarray)



testarray2.append(X[0])



X = np.array(X)
X = tf.cast(X, tf.float32)
#X = X.astype('float32') / 255

#Y = Y.astype('float32') / 255

print("X SHAPE", X.shape)
print(len(Y))


##
#from keras import layers
#from keras import models
#from keras.utils import to_categorical
#model = models.Sequential()
#model.add(layers.Conv2D(32, (2, 2), activation='relu', input_shape=(8,8,1)))
#model.summary()
#model.add(layers.MaxPooling2D((3, 3)))
##model.add(layers.Conv2D(64, (2, 2), activation='relu'))
##model.add(layers.MaxPooling2D((2, 2)))
#model.add(layers.Conv2D(64, (2, 2), activation='relu'))
#model.add(layers.Flatten())
#model.add(layers.Dense(64, activation='relu'))
#model.add(layers.Dense(1, activation='sigmoid'))

#model.summary()
#board = to_categorical(X)
#result = to_categorical(Y)

#model.compile(optimizer='rmsprop',
#              loss='binary_crossentropy',
#              metrics=['accuracy'])
#model.fit(board, result, epochs=5, batch_size=64)

##
        #handler = chess.uci.InfoHandler()
        #engine = chess.uci.popen_engine('...\stockfish_8_x64')  # give correct address of your engine here
        #engine.info_handlers.append(handler)

        # give your position to the engine:
        #engine.position(board)

        # Set your evaluation time, in ms:
        #evaltime = 5000  # so 5 seconds
        #evaluation = engine.go(movetime=evaltime)

        # print best move, evaluation and mainline:
        #print ('best move: ', board.san(evaluation[0]))
        #print ('evaluation value: ', handler.info["score"][1].cp / 100.0)
        #print ('Corresponding line: ', board.variation_san(handler.info["pv"][1]))




            # UCI string for a move to do...


Using TensorFlow backend.


<built-in function getcwd>
[Move.from_uci('g1h3'), Move.from_uci('g1f3'), Move.from_uci('b1c3'), Move.from_uci('b1a3'), Move.from_uci('h2h3'), Move.from_uci('g2g3'), Move.from_uci('f2f3'), Move.from_uci('e2e3'), Move.from_uci('d2d3'), Move.from_uci('c2c3'), Move.from_uci('b2b3'), Move.from_uci('a2a3'), Move.from_uci('h2h4'), Move.from_uci('g2g4'), Move.from_uci('f2f4'), Move.from_uci('e2e4'), Move.from_uci('d2d4'), Move.from_uci('c2c4'), Move.from_uci('b2b4'), Move.from_uci('a2a4')]
hello
. . . . . . k .
. b . . r p b .
. . . p . . p .
. P . . . n . p
r . . . p . . .
B R . . . . . .
P . . . . P P P
. . . R N B K .
['Aagooog.pgn', 'BAAtestingng.pgn', 'KingBase2019-A00-A39.pgn', 'KingBase2019-A40-A79.pgn', 'KingBase2019-A80-A99.pgn', 'KingBase2019-B00-B19.pgn', 'KingBase2019-B20-B49.pgn', 'KingBase2019-B50-B99.pgn', 'KingBase2019-C00-C19.pgn', 'KingBase2019-C20-C59.pgn', 'KingBase2019-C60-C99.pgn', 'KingBase2019-D00-D29.pgn', 'KingBase2019-D30-D69.pgn', 'KingBase2019-D70-D99.pgn', 'KingB

In [2]:

print(Y[700])
print(X[700])
print(X.shape)


-1
tf.Tensor(
[[[ 4.]
  [ 2.]
  [ 3.]
  [ 5.]
  [ 6.]
  [ 3.]
  [ 0.]
  [ 4.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 2.]
  [ 1.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 7.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 7.]
  [ 0.]]

 [[ 7.]
  [ 7.]
  [ 0.]
  [ 7.]
  [ 7.]
  [ 7.]
  [ 0.]
  [ 7.]]

 [[10.]
  [ 8.]
  [ 9.]
  [11.]
  [12.]
  [ 9.]
  [ 8.]
  [10.]]], shape=(8, 8, 1), dtype=float32)
(8059, 8, 8, 1)


In [4]:
from keras import layers
from keras import models
from keras.utils import to_categorical


model = models.Sequential()


model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=2, padding='same', activation='relu', input_shape=(8,8,1))) 
#model.add(tf.keras.layers.MaxPooling2D(pool_size=2))
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=2, padding='same', activation='relu')) 
#model.add(tf.keras.layers.MaxPooling2D(pool_size=2))
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
#model.add(tf.keras.layers.Dense(2, activation='softmax'))
model.add(tf.keras.layers.Dense(2, activation='softmax'))

model.summary()



board = to_categorical(X)
result = to_categorical(Y)

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              #loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(board, result, epochs=2, batch_size=32)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 8, 8, 32)          160       
_________________________________________________________________
dropout (Dropout)            (None, 8, 8, 32)          0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 8, 64)          8256      
_________________________________________________________________
dropout_1 (Dropout)          (None, 8, 8, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 4096)              0         
_________________________________________________________________
dense (Dense)                (None, 256)               1048832   
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0

ValueError: Error when checking input: expected conv2d_input to have shape (8, 8, 1) but got array with shape (8, 8, 13)

Test small trained data sample with a 8X8 chess board for an analysis.

In [3]:
board3 = chess.Board("6k1/1b2rpb1/3p2p1/1P3n1p/r3p3/BR6/P4PPP/3RNBK1 b - - 0 26") #Black won
board4 = chess.Board("2R5/1r3k2/6p1/3R1p1p/4p3/r7/P5Pb/4NK2 w - - 0 42") #Black won from train data
board5 = chess.Board("3r4/6R1/7P/4p1K1/4k3/8/3p4/8 w - - 0 48") #Black won
board6 = chess.Board("2rr2k1/p4p2/1P4pp/5P2/8/5N2/1bp1BPPP/2R3K1 w - - 1 29") #Black won
board7 = chess.Board("1r3bk1/4r1q1/1p1p2p1/p1pPp1N1/P1P1PnQ1/3nBPN1/1P5R/5K1R w - - 4 32") #White won
board8 = chess.Board("rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1") #white 1 pawn lol
board9 = chess.Board("8/6k1/1p1R4/3P4/2PbNr2/pP1K4/P4P2/8 b - - 4 42") #White won
board10 = chess.Board("3r3k/ppq4p/2r5/5p2/3Q1P2/5P2/PP5P/1B2R1RK b - - 0 32") #White won
boardbl = chess.Board("rnbqkb1r/pppppppp/5n2/8/4P3/5Q2/PPPP1PPP/RNB1KBNR b KQkq - 2 2")
testgame = np.zeros(64, np.uint32)
for i in range(64):
    positionn = boardbl.piece_at(i)
    if positionn is not None:
        # print(i, pp.symbol())
        testgame[i] = {"P": 1, "N": 2, "B": 3, "R": 4, "Q": 5, "K": 6, "p": 7, "n": 8, "b": 9, "r": 10, "q": 11, "k": 12}[positionn.symbol()]

testgame=testgame.reshape(1,8,8,1)
print(testgame.shape)
testgame = np.array(testgame)
testgame = tf.cast(testgame, tf.float32)
print(testgame)
#testgame = testgame.astype('float32') / 255
print(type(testgame))
prediction=model.predict_classes(np.array(testgame))
prediction1=model.predict(np.array(testgame))
#prediction1=model.predict(testgame)

print(prediction)
print(prediction1)
batch_size=64
#score = model.evaluate(X, Y, batch_size=batch_size, verbose=1)
#print(score[800])
#print(loss, metrics = model.evaluate(X, Y))
#print(X[2])
#print(Y[7])

(1, 8, 8, 1)
tf.Tensor(
[[[[ 4.]
   [ 2.]
   [ 3.]
   [ 0.]
   [ 6.]
   [ 3.]
   [ 2.]
   [ 4.]]

  [[ 1.]
   [ 1.]
   [ 1.]
   [ 1.]
   [ 0.]
   [ 1.]
   [ 1.]
   [ 1.]]

  [[ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 5.]
   [ 0.]
   [ 0.]]

  [[ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 1.]
   [ 0.]
   [ 0.]
   [ 0.]]

  [[ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 0.]]

  [[ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 0.]
   [ 8.]
   [ 0.]
   [ 0.]]

  [[ 7.]
   [ 7.]
   [ 7.]
   [ 7.]
   [ 7.]
   [ 7.]
   [ 7.]
   [ 7.]]

  [[10.]
   [ 8.]
   [ 9.]
   [11.]
   [12.]
   [ 9.]
   [ 0.]
   [10.]]]], shape=(1, 8, 8, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


NameError: name 'model' is not defined

In [ ]:
kk=0.05177836*255
print(kk)

ko=0.9482217*255
print(ko)


/255, castfloat32
3 - 0.23957638 0.76042354
4 - 0.23200318 0.7679968 
5 - 0.24216312 0.7578368 
6 - 0.23104927 0.7689507 Black 3-6 win
7 - 0.24210371 0.75789624  White 7-10 win
8 - 0.28996933 0.7100306 
9 - 0.25045803 0.749542  
10 - 0.2229797 0.7770202
11 -

[[0.28810897 0.71189106]]
[[0.26480824 0.73519176]] good for white
[[0.26412678 0.7358732 ]] really good for black
[[0.26818013 0.73181987]]